In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno

pd.set_option('display.max_columns', None)
sns.set_theme(style='whitegrid')

df=pd.read_csv('../data/raw/salary_benchmark.csv')

In [5]:
df.head()

,employee_id,age,gender,education_level,job_title,seniority_level,years_experience,years_at_company,industry,company_size,location,performance_rating,num_promotions,num_certifications,remote_ratio,col_index,base_salary
0,EMP003941,26,Male,PhD,Data Scientist,Mid,0.4,0.4,Finance,Enterprise (5000+),Boston,3.0,1,3.0,0.75,1.18,154000.0
1,EMP005264,21,Male,Bachelor's,DevOps Engineer,mid-level,7.1,0.8,Tech,Startup (<50),Remote,3.0,2,1.0,0.50,1.00,163100.0
2,EMP004570,32,Female,mba,DevOps Engineer,Principal,19.8,3.8,Tech,Mid (200-1000),New York,2.0,0,0.0,0.50,1.32,256700.0
3,EMP001416,26,Male,High School,Finance Analyst,Mid,0.4,0.4,Government,Mid (200-1000),Denver,5.0,0,2.0,0.50,1.06,57800.0
4,EMP000450,21,Male,High School,ML Engineer,Mid,10.6,1.9,Consulting,Large (1000-5000),Seattle,3.0,1,2.0,0.25,1.20,133300.0

In [14]:
display(df.shape)
df.info()

df_copy = df.copy()


cat_cols = ['education_level', 'job_title', 'seniority_level']
drop_cols = ['employee_id']

fix_cols =['company_size', 'job_title']

numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
# display(numeric_cols)

(5535, 17)

<class 'pandas.DataFrame'>
RangeIndex: 5535 entries, 0 to 5534
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         5535 non-null   str
 1   age                 5535 non-null   int64
 2   gender              5535 non-null   str
 3   education_level     5535 non-null   str
 4   job_title           5535 non-null   str
 5   seniority_level     5535 non-null   str
 6   years_experience    5257 non-null   float64
 7   years_at_company    5535 non-null   float64
 8   industry            5535 non-null   str
 9   company_size        5535 non-null   str
 10  location            5535 non-null   str
 11  performance_rating  5203 non-null   float64
 12  num_promotions      5535 non-null   int64
 13  num_certifications  5312 non-null   float64
 14  remote_ratio        5535 non-null   float64
 15  col_index           5535 non-null   float64
 16  base_salary         5535 non-null   float64
dtypes: float64(7), int64(2), str(8)
memory usage: 735.2 KB

['age',
 'years_experience',
 'years_at_company',
 'performance_rating',
 'num_promotions',
 'num_certifications',
 'remote_ratio',
 'col_index',
 'base_salary']

In [15]:
df.head()

,employee_id,age,gender,education_level,job_title,seniority_level,years_experience,years_at_company,industry,company_size,location,performance_rating,num_promotions,num_certifications,remote_ratio,col_index,base_salary
0,EMP003941,26,Male,PhD,Data Scientist,Mid,0.4,0.4,Finance,Enterprise (5000+),Boston,3.0,1,3.0,0.75,1.18,154000.0
1,EMP005264,21,Male,Bachelor's,DevOps Engineer,mid-level,7.1,0.8,Tech,Startup (<50),Remote,3.0,2,1.0,0.50,1.00,163100.0
2,EMP004570,32,Female,mba,DevOps Engineer,Principal,19.8,3.8,Tech,Mid (200-1000),New York,2.0,0,0.0,0.50,1.32,256700.0
3,EMP001416,26,Male,High School,Finance Analyst,Mid,0.4,0.4,Government,Mid (200-1000),Denver,5.0,0,2.0,0.50,1.06,57800.0
4,EMP000450,21,Male,High School,ML Engineer,Mid,10.6,1.9,Consulting,Large (1000-5000),Seattle,3.0,1,2.0,0.25,1.20,133300.0

In [28]:
# df_copy['job_title'].value_counts()
# df_copy['education_level'].value_counts()
# display(df_copy['seniority_level'].value_counts())
# display(df_copy['company_size'].value_counts())

fix_cols = ['job_title', 'education_level', 'seniority_level']
missing_cols = ['performance_rating', 'num_certfications', 'years_experience']

In [ ]:
for col in fix_cols:
    df_copy[col] = df_copy[col].str.strip().str.title()
    print(f"Unique values in {col}: {df_copy[col].value_counts().index.tolist()}")
    
value_map = {
    "ML Engineer": "Ml Engineer",
    "HR Specialist": "Hr Specialist",
    "Bachelor": ["Bachelor'S", "Bachelors"],
    "Master": ["Master'S", "Masters", "Mba"],
    "Associate": "Associate'S",
    "Phd": ["Ph.D.", "Phd", "Doctorate"],
}


for col in fix_cols:
    df_copy[col] = df_copy[col].replace(value_map.get(col, {}))

Unique values in job_title: ['Software Engineer', 'Data Analyst', 'Data Scientist', 'Ml Engineer', 'Business Analyst', 'Finance Analyst', 'Devops Engineer', 'Product Manager', 'Marketing Analyst', 'Hr Specialist']
Unique values in education_level: ["Bachelor'S", "Master'S", "Associate'S", 'Mba', 'High School', 'Phd', 'Master', 'Bachelors', 'Masters']
Unique values in seniority_level: ['Mid', 'Senior', 'Junior', 'Lead', 'Principal', 'Mid-Level']